### ISSUE TITLE
Wrong type of comment used for .appcache file

### ISSUE THREAD

**Issue by rejhgadellaa** [mjeanroy/gulp-header-comment#14]
I have a gulp task that does:

```
gulp.task("app-appcache", function(){
	return gulp.src("src/somefile.appcache")
	.pipe(headerComment("Version: <%= moment().format() %>"))
	.pipe(gulp.dest("dst/"))
	;
});
```

but header-comment uses /** */ style comments (which are not supported in appcache files):

```
/**
 * Version: 2017-06-25T16:50:12+02:00
 */
```

It says in the docs that '#' will be used when it's not a css, js or html file?

**Comment by mjeanroy** [comment]
@rejhgadellaa The problem will be fixed with this [pull request](https://github.com/3rd-Eden/commenting/pull/4) on the commenting package. Once released, I'll push an update.

Thanks for your report!

**Comment by mjeanroy** [comment]
@rejhgadellaa Version 0.2.1 has been released with the fix.
