### ISSUE TITLE
How can I prepend each file with its name?

### ISSUE THREAD

**Issue by lmoroz** [mjeanroy/gulp-header-comment#381]
Hello.

I need prepend each scss chunk-file with its filename.
Can I do this with gulp-header-comment ?

**Comment by mjeanroy** [comment]
Hi @lmoroz,
I just published version 0.10.0 with this feature (it was not possible before).

See [here](https://github.com/mjeanroy/gulp-header-comment/blob/a44b14237258769b3c6f5e7dbaa8364a1ddeb40a/test/it.spec.js#L124) what you can use now.

Basically, use a template and you will have access to a `file` object where you can access the file name, full path and relative path (relative to the root of your package).
