### ISSUE TITLE
Comment won't get replaced when using the same source and destination file

### ISSUE THREAD

**Issue by alvarotrigo** [mjeanroy/gulp-header-comment#53]
Thanks for the module! Almost what I'm looking for to update a comment in static html files!

I want to use the same file for source and destination. 
I just want to process it to add a new version number.
Unfortunately this module only appends comments and won't be able to replace the existing one, generating this way multiple repeated version comments each time I run the script:

```javascript
//including date comment 
gulp.task('html-version', function() {
    gulp.src([
        './_includes/footer.html',
        './_includes/head.html',
        ])
        .pipe(headerComment('Generated on <%= Date.now() %>'))
        .pipe(gulp.dest('./_includes/'));
});
```

End up generating the following when running it for a second time: 

```html
<!--
 // Generated on 1513269242418
-->

<!--
 // Generated on 1513269240810
-->
```

I would expect it to update the previous comment instead.

**Comment by alvarotrigo** [comment]
I ended up modifying the module myself. 
In `index.js` Instead of:

```javascript
        // Just prepend content.
        file.contents = new Buffer(header + file.contents);
```

I added:

```javascript
var myRegex = new RegExp("<!--\n\\s\/\/\\sGenerated(.*?)\\s-->\n\n", "g");
        var stringContent = file.contents.toString();
        var matches = myRegex.exec(stringContent);

        if(matches){
          file.contents =  stringToBuffer(stringContent.replace( myRegex, header));
        }else{
          file.contents = new Buffer(header + file.contents);
        }
```

**Comment by mjeanroy** [comment]
Hi @alvarotrigo,

Thanks for your comment, but I'm not sure it should be the responsibility of this plugin to remove previous comment. Did you try with `gulp-strip-banner` or `gulp-strip-comment` plugins?

**Comment by alvarotrigo** [comment]
Hi @mjeanroy. 
I'm don't really want to remove all comments, just the one generated with gulp-header-comment. 

But I understand. This component only adds comments and doesn't expect the input and output to be the same file. 
I'll just use my mod :) Thanks tho!
